package net.tabor.seedcity.client;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Generated by tools/build_collector_assets.py; edit the source, then regenerate. */
public final class CollectorMesh {
    private CollectorMesh() {}
    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
		PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
				, PartPose.offset(0F, 24F, 0F));
		PartDefinition torso = body.addOrReplaceChild("torso", CubeListBuilder.create()
				.texOffs(0, 0).addBox(-5F, 0F, -3F, 10F, 11F, 7F, new CubeDeformation(0.012F)) // torso
				.texOffs(36, 0).addBox(-4F, 2F, -3.5F, 8F, 7F, 1F, new CubeDeformation(0.0125F)) // apron
				.texOffs(56, 0).addBox(-3F, 3F, -3.7F, 6F, 4F, 1F, new CubeDeformation(0.013F)) // apron_center
				.texOffs(72, 0).addBox(-5F, 9F, -3.5F, 10F, 2F, 8F, new CubeDeformation(0.0135F)) // belt
				.texOffs(110, 0).addBox(-1F, 9F, -3.8F, 2F, 2F, 1F, new CubeDeformation(0.014F)) // belt_buckle
				.texOffs(118, 0).addBox(-5F, -5F, 4F, 10F, 15F, 5F, new CubeDeformation(0.0145F)) // pack
				.texOffs(150, 0).addBox(-5F, -6F, 4F, 10F, 2F, 5F, new CubeDeformation(0.015F)) // pack_rim
				.texOffs(182, 0).addBox(-4F, -4F, 8.5F, 1F, 14F, 1F, new CubeDeformation(0.0155F)) // pack_strap_right
				.texOffs(188, 0).addBox(3F, -4F, 8.5F, 1F, 14F, 1F, new CubeDeformation(0.016F)) // pack_strap_left
				.texOffs(194, 0).addBox(-5F, 9F, 4F, 10F, 2F, 5F, new CubeDeformation(0.0165F)) // pack_bottom
				.texOffs(226, 0).addBox(-4F, -11F, 4F, 5F, 6F, 4F, new CubeDeformation(0.017F)) // stone_cargo
				.texOffs(0, 22).addBox(-3F, -13F, 5F, 3F, 2F, 3F, new CubeDeformation(0.0175F)) // stone_cargo_top
				.texOffs(14, 22).addBox(1F, -12F, 4F, 3F, 7F, 4F, new CubeDeformation(0.018F)) // log_cargo
				.texOffs(30, 22).addBox(1F, -12.1F, 4F, 3F, 1F, 4F, new CubeDeformation(0.0185F)) // log_cut_end
				.texOffs(46, 22).addBox(0F, -8F, 7F, 4F, 3F, 3F, new CubeDeformation(0.019F)) // log_cargo_short
				, PartPose.offset(0F, -21F, 0F));
		PartDefinition head = torso.addOrReplaceChild("head", CubeListBuilder.create()
				.texOffs(62, 22).addBox(-4F, -8F, -4F, 8F, 8F, 8F, new CubeDeformation(0.0195F)) // helmet
				.texOffs(96, 22).addBox(-4F, -8.1F, -4F, 8F, 2F, 8F, new CubeDeformation(0.02F)) // helmet_crown
				.texOffs(130, 22).addBox(-4.5F, -6.5F, -4.5F, 9F, 1F, 9F, new CubeDeformation(0.0205F)) // helmet_brim
				.texOffs(168, 22).addBox(-3.5F, -5.5F, -4.08F, 7F, 4F, 1F, new CubeDeformation(0.021F)) // face_inset
				.texOffs(186, 22).addBox(-3F, -4.75F, -4.16F, 2F, 2F, 1F, new CubeDeformation(0.0215F)) // eye_right
				.texOffs(194, 22).addBox(1F, -4.75F, -4.16F, 2F, 2F, 1F, new CubeDeformation(0.022F)) // eye_left
				.texOffs(202, 22).addBox(-2F, -8F, -4.7F, 4F, 2F, 1F, new CubeDeformation(0.0225F)) // lamp_bracket
				.texOffs(214, 22).addBox(-1.5F, -8F, -5F, 3F, 2F, 1F, new CubeDeformation(0.023F)) // lamp_rim
				.texOffs(224, 22).addBox(-1F, -8F, -5.3F, 2F, 2F, 1F, new CubeDeformation(0.0235F)) // lamp_light
				, PartPose.offset(0F, 0F, 0F));
		PartDefinition right_arm = torso.addOrReplaceChild("right_arm", CubeListBuilder.create()
				.texOffs(232, 22).addBox(-2F, -1F, -2F, 4F, 4F, 5F, new CubeDeformation(0.024F)) // right_shoulder
				.texOffs(0, 40).addBox(-1.5F, 3F, -1.5F, 3F, 4F, 3F, new CubeDeformation(0.0245F)) // right_upper_arm
				.texOffs(14, 40).addBox(-2F, 6F, -2F, 4F, 5F, 4F, new CubeDeformation(0.025F)) // right_gauntlet
				.texOffs(32, 40).addBox(-1.5F, 10F, -1.5F, 3F, 3F, 3F, new CubeDeformation(0.0255F)) // right_hand
				, PartPose.offset(-7F, 1F, 0F));
		PartDefinition left_arm = torso.addOrReplaceChild("left_arm", CubeListBuilder.create()
				.texOffs(46, 40).addBox(-2F, -1F, -2F, 4F, 4F, 5F, new CubeDeformation(0.026F)) // left_shoulder
				.texOffs(66, 40).addBox(-1.5F, 3F, -1.5F, 3F, 4F, 3F, new CubeDeformation(0.0265F)) // left_upper_arm
				.texOffs(80, 40).addBox(-2F, 6F, -2F, 4F, 5F, 4F, new CubeDeformation(0.027F)) // left_gauntlet
				.texOffs(98, 40).addBox(-1.5F, 10F, -1.5F, 3F, 3F, 3F, new CubeDeformation(0.0275F)) // left_hand
				, PartPose.offset(7F, 1F, 0F));
		PartDefinition right_leg = body.addOrReplaceChild("right_leg", CubeListBuilder.create()
				.texOffs(112, 40).addBox(-2F, 0F, -2F, 4F, 5F, 4F, new CubeDeformation(0.028F)) // right_thigh
				.texOffs(130, 40).addBox(-2F, 4F, -2F, 4F, 4F, 4F, new CubeDeformation(0.0285F)) // right_shin
				.texOffs(148, 40).addBox(-2.5F, 8F, -3F, 5F, 2F, 6F, new CubeDeformation(0.029F)) // right_boot
				, PartPose.offset(-3F, -10F, 0F));
		PartDefinition left_leg = body.addOrReplaceChild("left_leg", CubeListBuilder.create()
				.texOffs(172, 40).addBox(-2F, 0F, -2F, 4F, 5F, 4F, new CubeDeformation(0.0295F)) // left_thigh
				.texOffs(190, 40).addBox(-2F, 4F, -2F, 4F, 4F, 4F, new CubeDeformation(0.03F)) // left_shin
				.texOffs(208, 40).addBox(-2.5F, 8F, -3F, 5F, 2F, 6F, new CubeDeformation(0.0305F)) // left_boot
				, PartPose.offset(3F, -10F, 0F));
        return LayerDefinition.create(mesh, 256, 256);
    }
}
