package net.tabor.seedcity.client;

import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;

/** Generated by tools/build_rectifier_assets.py; edit the source, then regenerate. */
public final class RectifierMesh {
    private RectifierMesh() {}
    public static LayerDefinition createLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
		PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
				.texOffs(0, 0).addBox(-2F, -12F, -2F, 4F, 5F, 4F) // neck
				.texOffs(18, 0).addBox(-5F, -8F, -3F, 10F, 14F, 6F) // torso
				.texOffs(52, 0).addBox(-4F, -7F, -4F, 8F, 9F, 2F) // chest_rim
				.texOffs(74, 0).addBox(-3F, -6F, -4.4F, 6F, 7F, 1F) // chest_socket
				.texOffs(90, 0).addBox(-2F, -5F, -4.65F, 4F, 5F, 1F) // core
				.texOffs(102, 0).addBox(-1F, -4F, -4.8F, 2F, 3F, 1F) // core_center
				.texOffs(110, 0).addBox(4F, -7F, -4F, 2F, 8F, 2F, new CubeDeformation(0.04F)) // chest_left
				.texOffs(120, 0).addBox(-6F, -7F, -4F, 2F, 8F, 2F, new CubeDeformation(0.04F)) // chest_right
				.texOffs(130, 0).addBox(-4F, -7F, 3F, 8F, 10F, 1F) // back_plate
				.texOffs(150, 0).addBox(-1F, -6F, 4F, 2F, 8F, 1F) // back_spine
				.texOffs(158, 0).addBox(-5.5F, 5F, -3.5F, 11F, 3F, 7F, new CubeDeformation(0.04F)) // belt
				.texOffs(196, 0).addBox(-2F, 5.5F, -4.5F, 4F, 2F, 1F, new CubeDeformation(0.06F)) // buckle
				.texOffs(208, 0).addBox(-2F, 7F, -4F, 4F, 12F, 1F) // tabard_trim
				.texOffs(220, 0).addBox(-1.5F, 7.5F, -4.2F, 3F, 11F, 1F) // tabard
				.texOffs(230, 0).addBox(-0.5F, 10F, -4.4F, 1F, 5F, 1F) // tabard_mark
				.texOffs(0, 22).addBox(-4.5F, 8F, -2.5F, 9F, 2F, 5F) // hip
				, PartPose.offset(0F, 2F, 0F));
		PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create()
				.texOffs(30, 22).addBox(-4F, -10F, -3.5F, 8F, 10F, 7F) // helmet
				.texOffs(62, 22).addBox(-4.5F, -10F, -4F, 9F, 3F, 8F, new CubeDeformation(0.04F)) // crown
				.texOffs(98, 22).addBox(-3F, -7F, -3.7F, 6F, 5F, 1F) // face_shadow
				.texOffs(114, 22).addBox(-0.5F, -7F, -3.9F, 1F, 5F, 1F, new CubeDeformation(0.04F)) // vertical_visor
				.texOffs(120, 22).addBox(-3.5F, -6F, -4F, 2F, 6F, 1F, new CubeDeformation(0.06F)) // cheek_right
				.texOffs(128, 22).addBox(1.5F, -6F, -4F, 2F, 6F, 1F, new CubeDeformation(0.06F)) // cheek_left
				, PartPose.offset(0F, -10F, 0F));
		PartDefinition right_arm = body.addOrReplaceChild("right_arm", CubeListBuilder.create()
				.texOffs(136, 22).addBox(-3F, -2F, -3F, 6F, 7F, 6F) // right_shoulder
				.texOffs(162, 22).addBox(-3.5F, -2F, -3.5F, 7F, 2F, 7F, new CubeDeformation(0.04F)) // right_shoulder_cap
				.texOffs(192, 22).addBox(-2F, 5F, -2F, 4F, 4F, 4F) // right_upper_arm
				.texOffs(210, 22).addBox(-1.5F, 8F, -1.5F, 3F, 2F, 3F) // right_elbow
				.texOffs(224, 22).addBox(-2.5F, 10F, -2.5F, 5F, 5F, 5F) // right_forearm
				.texOffs(0, 41).addBox(-2.5F, 14F, -2.5F, 5F, 1F, 5F, new CubeDeformation(0.04F)) // right_wrist_band
				.texOffs(22, 41).addBox(-2F, 15F, -2F, 4F, 3F, 4F) // right_hand
				, PartPose.offset(-9F, -7F, 0F));
		PartDefinition left_arm = body.addOrReplaceChild("left_arm", CubeListBuilder.create()
				.texOffs(148, 41).addBox(-3F, -2F, -3F, 6F, 7F, 6F) // left_shoulder
				.texOffs(174, 41).addBox(-3.5F, -2F, -3.5F, 7F, 2F, 7F, new CubeDeformation(0.04F)) // left_shoulder_cap
				.texOffs(204, 41).addBox(-2F, 5F, -2F, 4F, 4F, 4F) // left_upper_arm
				.texOffs(222, 41).addBox(-1.5F, 8F, -1.5F, 3F, 2F, 3F) // left_elbow
				.texOffs(0, 56).addBox(-2.5F, 10F, -2.5F, 5F, 5F, 5F) // left_forearm
				.texOffs(22, 56).addBox(-2.5F, 14F, -2.5F, 5F, 1F, 5F, new CubeDeformation(0.04F)) // left_wrist_band
				.texOffs(44, 56).addBox(-2F, 15F, -2F, 4F, 3F, 4F) // left_hand
				, PartPose.offset(9F, -7F, 0F));
		PartDefinition right_leg = body.addOrReplaceChild("right_leg", CubeListBuilder.create()
				.texOffs(40, 41).addBox(-2F, 0F, -2F, 4F, 6F, 4F) // right_thigh
				.texOffs(58, 41).addBox(-2F, 6F, -2F, 4F, 2F, 4F) // right_knee
				.texOffs(76, 41).addBox(-2.5F, 7F, -2.5F, 5F, 5F, 5F) // right_greave
				.texOffs(98, 41).addBox(-2.5F, 7F, -2.5F, 5F, 2F, 5F, new CubeDeformation(0.04F)) // right_greave_band
				.texOffs(120, 41).addBox(-3F, 12F, -4F, 6F, 2F, 7F) // right_boot
				, PartPose.offset(-3.5F, 8F, 0F));
		PartDefinition left_leg = body.addOrReplaceChild("left_leg", CubeListBuilder.create()
				.texOffs(62, 56).addBox(-2F, 0F, -2F, 4F, 6F, 4F) // left_thigh
				.texOffs(80, 56).addBox(-2F, 6F, -2F, 4F, 2F, 4F) // left_knee
				.texOffs(98, 56).addBox(-2.5F, 7F, -2.5F, 5F, 5F, 5F) // left_greave
				.texOffs(120, 56).addBox(-2.5F, 7F, -2.5F, 5F, 2F, 5F, new CubeDeformation(0.04F)) // left_greave_band
				.texOffs(142, 56).addBox(-3F, 12F, -4F, 6F, 2F, 7F) // left_boot
				, PartPose.offset(3.5F, 8F, 0F));
		PartDefinition lantern = right_arm.addOrReplaceChild("lantern", CubeListBuilder.create()
				.texOffs(170, 56).addBox(-1.5F, 0F, -0.5F, 3F, 1F, 1F) // lantern_handle_top
				.texOffs(180, 56).addBox(-1.5F, 1F, -0.5F, 1F, 2F, 1F) // lantern_handle_left
				.texOffs(186, 56).addBox(0.5F, 1F, -0.5F, 1F, 2F, 1F) // lantern_handle_right
				.texOffs(192, 56).addBox(-2.5F, 3F, -2.5F, 5F, 1F, 5F) // lantern_cap
				.texOffs(214, 56).addBox(-1.5F, 4F, -1.5F, 3F, 4F, 3F) // lantern_light
				.texOffs(228, 56).addBox(-2.5F, 8F, -2.5F, 5F, 1F, 5F) // lantern_base
				.texOffs(250, 56).addBox(-2.5F, 4F, -2.5F, 1F, 4F, 1F) // lantern_post_-11.5_-2.5
				.texOffs(0, 68).addBox(-2.5F, 4F, 1.5F, 1F, 4F, 1F) // lantern_post_-11.5_1.5
				.texOffs(6, 68).addBox(1.5F, 4F, -2.5F, 1F, 4F, 1F) // lantern_post_-7.5_-2.5
				.texOffs(12, 68).addBox(1.5F, 4F, 1.5F, 1F, 4F, 1F) // lantern_post_-7.5_1.5
				, PartPose.offset(0F, 17F, 0F));
		PartDefinition wrench = left_arm.addOrReplaceChild("wrench", CubeListBuilder.create()
				.texOffs(18, 68).addBox(-0.5F, -1F, -0.5F, 1F, 7F, 1F) // wrench_handle
				.texOffs(24, 68).addBox(-1F, 5F, -1F, 2F, 2F, 2F, new CubeDeformation(0.04F)) // wrench_neck
				.texOffs(34, 68).addBox(-2F, 7F, -1F, 4F, 1F, 2F) // wrench_base
				.texOffs(48, 68).addBox(-2F, 8F, -1F, 1F, 3F, 2F) // wrench_jaw_left
				.texOffs(56, 68).addBox(1F, 8F, -1F, 1F, 3F, 2F) // wrench_jaw_right
				, PartPose.offset(0F, 17F, -1F));
        return LayerDefinition.create(mesh, 256, 256);
    }
}
